# 针对 v2.0.0 版本的 nginx 配置示例
# 主要是针对“Server Actions”、“日志管理”和“上传资源”功能的配置

# Nginx Configuration Example for Version v2.0.0
# Mainly configuring the "Server Actions", "Log Management", and "Upload Resources" features

server {
 ...
 location / {
   proxy_pass http://127.0.0.1:3000; # website服务端口（自定义）
   proxy_set_header Host              $host;  # “Server Actions” 功能
   proxy_set_header X-Forwarded-Proto $scheme; # “Server Actions” 功能
   proxy_set_header X-Real-IP         $remote_addr; # “日志管理” 功能
   proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for; # “日志管理” 功能
 }

 location /api/auth/upload {
  client_max_body_size 21M; # “上传资源” 功能
  proxy_pass http://127.0.0.1:3000; # website服务端口（自定义）
 }
 
}
